from pathlib import Path
from trainer_and_simulator_functions import launch_inference_sim

def batch_inference(
        run_dir: Path,
        unity_env_path: Path,
        patched_yaml_path: Path,
        out_root: Path,
        episodes: int,
        base_port: int = 5015,
        timeout_s: int = 300,
        seed: int = 17,
        run_ids: list[str] | None = None,
        results_subdir: str = "",
        behaviour_name: str = "OctagonAgentSolo",
        trial_seq: Path | str | None = None,
):
    '''
    Run inference sequentially on trained models under run_dir/results/<results_subdir>/.
    If run_ids is provided, only those leaf run IDs are used.
    Otherwise, all subdirectories under run_dir/results/<results_subdir>/ are used.
    trial_seq: optional path to a predetermined trial-sequence JSON (generated by
    trial_sequences/generate_trial_sequence.py). When supplied, every model
    replays the same string of trials and the sim stops when the sequence is
    exhausted; when None, trials are generated randomly by the Unity build.
    '''
    run_dir = Path(run_dir)
    results_root = run_dir / "results" / results_subdir

    if run_ids is None:
        run_ids = sorted([
            d.name for d in results_root.iterdir() if d.is_dir()
        ])

    if not run_ids:
        raise FileNotFoundError(f"No run directories found in {results_root}")

    print(f"Found {len(run_ids)} models to run inference on: {run_ids}")

    logs = {}
    for i, run_id in enumerate(run_ids):
        print(f"\n=== [{i+1}/{len(run_ids)}] Running inference: {run_id} ===")
        full_run_id = f"{results_subdir}/{run_id}" if results_subdir else run_id
        # Mirror the trained-model tree under out_root, i.e.
        # out_root/<results_subdir>/<run_id>  ->  out_root/2606/260624/260624_0001
        out_path = Path(out_root) / full_run_id
        try:
            log = launch_inference_sim(
                run_dir=run_dir,
                unity_env_path=unity_env_path,
                patched_yaml_path=patched_yaml_path,
                train_run_id=full_run_id,
                out_path=out_path,
                episodes=episodes,
                base_port=base_port,
                timeout_s=timeout_s,
                seed=seed,
                trial_seq=trial_seq,
            )
            logs[run_id] = log
            print(f"=== Finished: {run_id} -> {log} ===")
        except Exception as e:
            print(f"=== FAILED: {run_id} — {e} ===")
            logs[run_id] = None

    return logs

# Helper function to find the latest .onnx file for a given run ID
# Currently unused
def find_latest_onnx(run_dir: Path, run_id: str) -> Path:
    candidates = list((run_dir /run_id / "OctagonAgentSolo").rglob("*.onnx"))
    
    if not candidates:
        raise FileNotFoundError(f"No .onnx found for {run_id}")
    
    return max(candidates, key=lambda p: p.stat().st_mtime)